<?php

return [
  [
    'name' => 'CustomGroup_fundraiser_workshift',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'fundraiser_workshift',
        'title' => 'Fundraiser Workshift',
        'extends' => 'Individual',
        'extends_entity_column_id' => NULL,
        'extends_entity_column_value' => [
          'Dialoger',
        ],
        'style' => 'Tab with table',
        'collapse_display' => FALSE,
        'help_pre' => '',
        'help_post' => '',
        'weight' => 40,
        'is_active' => TRUE,
        'is_multiple' => TRUE,
        'min_multiple' => NULL,
        'max_multiple' => NULL,
        'collapse_adv_display' => TRUE,
        'created_date' => '2023-08-23 13:53:51',
        'is_reserved' => FALSE,
        'is_public' => TRUE,
        'icon' => 'fa-clock-o',
        'table_name' => 'civicrm_value_fundraiser_workshift',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_fundraiser_workshift_CustomField_external_id',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'fundraiser_workshift',
        'name' => 'external_id',
        'label' => 'External ID',
        'data_type' => 'Int',
        'html_type' => 'Text',
        'default_value' => NULL,
        'is_required' => TRUE,
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'help_pre' => NULL,
        'help_post' => NULL,
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => NULL,
        'options_per_line' => NULL,
        'text_length' => 255,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'external_id',
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => TRUE,
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_fundraiser_workshift_CustomField_workshift_id',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'fundraiser_workshift',
        'name' => 'workshift_id',
        'label' => 'Workshift ID',
        'data_type' => 'Int',
        'html_type' => 'Text',
        'default_value' => NULL,
        'is_required' => TRUE,
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'help_pre' => NULL,
        'help_post' => NULL,
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => NULL,
        'options_per_line' => NULL,
        'text_length' => 255,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'workshift_id',
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => TRUE,
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_fundraiser_workshift_CustomField_date',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'fundraiser_workshift',
        'name' => 'date',
        'label' => 'Date',
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'default_value' => NULL,
        'is_required' => TRUE,
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'help_pre' => NULL,
        'help_post' => NULL,
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => NULL,
        'options_per_line' => NULL,
        'text_length' => 255,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => 'yy-mm-dd',
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'date',
        'serialize' => 0,
        'filter' => NULL,        'in_selector' => TRUE,
        'option_group_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_fundraiser_workshift_CustomField_hours',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'fundraiser_workshift',
        'name' => 'hours',
        'label' => 'Hours',
        'data_type' => 'Float',
        'html_type' => 'Text',
        'default_value' => NULL,
        'is_required' => NULL,
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'help_pre' => NULL,
        'help_post' => NULL,
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => NULL,
        'options_per_line' => NULL,
        'text_length' => 255,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'hours',
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => TRUE,
        'option_group_id' => NULL,
      ],
    ],
  ],
];