<?php

return [
  'donutapp_campaign_map' => [
    'name'        => 'donutapp_campaign_map',
    'type'        => 'Array',
    'html_type'   => 'text',
    'default'     => [],
    'add'         => '1.3',
    'title'       => ts('DonutApp: Mapping of DonutApp campaigns to Civi campaigns'),
    'is_domain'   => 1,
    'is_contact'  => 0,
    'description' => ts('This maps campaigns in DonutApp to campaigns in CiviCRM.'),
  ],
  'donutapp_order_type_map' => [
    'name'        => 'donutapp_order_type_map',
    'type'        => 'Array',
    'html_type'   => 'text',
    'default'     => [],
    'add'         => '2.2',
    'title'       => ts('DonutApp: Mapping of membership type name to order type name'),
    'is_domain'   => 1,
    'is_contact'  => 0,
    'description' => ts('This maps membership types to order types. Key "default" can be used as a fallback.'),
  ],
  'donutapp_membership_type_map' => [
    'name'        => 'donutapp_membership_type_map',
    'type'        => 'Array',
    'html_type'   => 'text',
    'default'     => [],
    'add'         => '2.3',
    'title'       => ts('DonutApp: Mapping of DD-only membership product names to Civi membership type names'),
    'is_domain'   => 1,
    'is_contact'  => 0,
    'description' => ts('This maps DD-only membership product names to Civi membership types. This is optional, membership type names are used as a fallback.'),
  ],
  'donutapp_sync_fundraiser_contact_details' => [
    'name'        => 'donutapp_sync_fundraiser_contact_details',
    'type'        => 'Boolean',
    'html_type'   => 'checkbox',
    'default'     => TRUE,
    'add'         => '2.4',
    'title'       => ts('DonutApp: Import Fundraiser Contact Details? (Email/Phone/Address)'),
    'is_domain'   => 1,
    'is_contact'  => 0,
    'description' => ts('Should synchronization of fundraisers include contact details like email, phone and address?'),
  ],
  'donutapp_workshift_customer_filter' => [
    'name'        => 'donutapp_workshift_customer_filter',
    'type'        => 'Array',
    'html_type'   => 'text',
    'default'     => NULL,
    'add'         => '2.4',
    'title'       => ts('DonutApp: Limit Workshift Import to customer IDs'),
    'is_domain'   => 1,
    'is_contact'  => 0,
    'description' => ts('Workshifts for which customer IDs should be imported?'),
  ],
];
